In [1]:
import cv2
import numpy as np


In [5]:
image = cv2.imread('img2.jpeg')

In [6]:
print(image.shape)

(30, 30, 3)


In [9]:
print(image.dtype)


uint8


In [7]:
image

array([[[  0,   0, 254],
        [  0,   0, 254],
        [  0,   0, 254],
        ...,
        [255,  12,   0],
        [255,  12,   0],
        [255,  12,   0]],

       [[  0,   0, 254],
        [  0,   1, 253],
        [  0,   1, 253],
        ...,
        [255,  12,   0],
        [255,  13,   0],
        [254,  12,   0]],

       [[  0,   0, 254],
        [  0,   1, 253],
        [  0,   1, 253],
        ...,
        [254,  12,   0],
        [255,  12,   0],
        [254,  12,   0]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  0, 255,  41],
        [  0, 255,  41],
        [  0, 255,  41]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  0, 255,  41],
        [  0, 255,  41],
        [  0, 255,  41]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  1, 255,  41],
        [  1, 255,  41],
        [  1, 255,  41]]

In [10]:
image[0][16:25]

array([[190,  15,  82],
       [204,   3,  37],
       [243,  10,   8],
       [255,  13,   0],
       [255,  13,   0],
       [252,  11,   2],
       [254,  11,   2],
       [255,  12,   0],
       [255,  12,   0]], dtype=uint8)

In [12]:
image[0][10:20]

array([[  0,   2, 251],
       [  0,   0, 254],
       [  0,   1, 254],
       [  7,   7, 239],
       [ 26,  28, 190],
       [  0,   0,  73],
       [190,  15,  82],
       [204,   3,  37],
       [243,  10,   8],
       [255,  13,   0]], dtype=uint8)

In [14]:
for i in range(30):
    for j in range(30):
        print(image[i][j])
    print()

[  0   0 254]
[  0   0 254]
[  0   0 254]
[  0   0 254]
[  0   0 254]
[  2   0 253]
[  2   0 254]
[  0   0 254]
[  0   0 254]
[  0   2 251]
[  0   2 251]
[  0   0 254]
[  0   1 254]
[  7   7 239]
[ 26  28 190]
[ 0  0 73]
[190  15  82]
[204   3  37]
[243  10   8]
[255  13   0]
[255  13   0]
[252  11   2]
[254  11   2]
[255  12   0]
[255  12   0]
[255  12   0]
[255  12   0]
[255  12   0]
[255  12   0]
[255  12   0]

[  0   0 254]
[  0   1 253]
[  0   1 253]
[  0   0 254]
[  0   0 254]
[  2   0 253]
[  2   1 251]
[  0   0 254]
[  0   0 254]
[  2   1 251]
[  2   2 250]
[  0   0 254]
[  0   1 254]
[  7   7 239]
[ 26  28 190]
[ 0  0 73]
[190  15  82]
[203   3  37]
[242  10   8]
[255  13   0]
[255  12   0]
[252  11   2]
[252  12   1]
[255  13   0]
[255  13   0]
[254  12   1]
[254  12   1]
[255  12   0]
[255  13   0]
[254  12   0]

[  0   0 254]
[  0   1 253]
[  0   1 253]
[  0   0 254]
[  0   0 254]
[  0   1 253]
[  2   1 251]
[  0   0 254]
[  0   0 254]
[  2   1 251]
[  2   1 251]
[  0   0 2